version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
volumes:
  psql-data:
