version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=scheduler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - psql-data:/var/lib/postgresql/data
    networks:
      - server
  backend:
    build:
      context: backend
      target: development
    restart: unless-stopped
    environment:
      - PG_DBNAME=scheduler
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
    volumes:
      - ./backend/src:/opt/src
      - backend-cache:/opt/target
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - server
      - client
  frontend:
    build:
      context: frontend
      target: development
    restart: unless-stopped
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/opt/src
      - ./frontend/static:/opt/static
    networks:
      - client
volumes:
  psql-data:
  backend-cache:
networks:
  server:
  client:
